[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true  # Add this line

# Enable file system permissions for deployment artifact generation
fs_permissions = [
    { access = "write", path = "./out/deployment.json" },
    { access = "write", path = "./out/abiMap.json" },
]

# Optional: Optimizer settings for production deployments
optimizer = true
optimizer_runs = 200

# Optional: Gas reporting
gas_reports = ["*"]

[profile.ci]
verbosity = 4

[profile.local]
# For anvil deployments
verbosity = 3